import { TestRedux } from 'components/testRedux'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Provider } from 'react-redux'
import { store } from 'store/store'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider store={store}>
        <TestRedux/>
      </Provider>

    </div>
  )
}

export default Home
